# Generated by Django 3.0.7 on 2020-06-21 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=60)),
                ('Last_Name', models.CharField(max_length=60)),
                ('Profile_Picture', models.CharField(max_length=50)),
                ('Email_Address', models.EmailField(max_length=254)),
                ('Phone_Number', models.CharField(max_length=31)),
                ('Room_Number', models.CharField(max_length=10)),
            ],
        ),
    ]
