# Generated by Django 3.0.7 on 2020-06-21 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='Subjects_Taught',
            field=models.CharField(default='', max_length=300, verbose_name='Subjects Taught'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Email_Address',
            field=models.EmailField(max_length=254, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='First_Name',
            field=models.CharField(max_length=60, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Last_Name',
            field=models.CharField(max_length=60, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Phone_Number',
            field=models.CharField(max_length=31, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Profile_Picture',
            field=models.CharField(max_length=50, verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Room_Number',
            field=models.CharField(max_length=10, verbose_name='Room Number'),
        ),
    ]
