# Generated by Django 3.0.7 on 2020-06-22 19:22

import directory.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_auto_20200621_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='Email_Address',
            field=models.EmailField(max_length=254, unique=True, validators=[directory.validators.validate_null], verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='First_Name',
            field=models.CharField(max_length=60, validators=[directory.validators.validate_null], verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Last_Name',
            field=models.CharField(max_length=60, validators=[directory.validators.validate_null], verbose_name='Last Name'),
        ),
    ]
